---
- hosts: centos
  become: true
  tasks:
  - name: Install httpd and mod_wsgi
    yum:
      name:
        - httpd
        - mod_wsgi
      state: latest
  - name: make sure httpd and firewalld is started
    systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - firewalld
      - httpd
  - name: Allow HTTP requests to the server
    shell: firewall-cmd --permanent --add-service=http
  - name: Reload for HTTP change to take effect
    shell: firewall-cmd --reload
  - name: Copy python project over
    copy:
      src: ./files/python/
      dest: /var/www/python
      owner: apache
      group: apache
  - name: Copy over configuration file for httpd
    copy:
      src: "./files/helloworld.conf"
      dest: /etc/httpd/conf.d/helloworld.conf
      owner: apache
      group: apache
  - name: Restart httpd for configuration changes to take effect
    systemd:
      state: restarted
      name: httpd
